### ISSUE TITLE
Cannot find module '../../@jridgewell/gen-mapping/dist/gen-mapping.umd.js' due to 0.3.6 build

### ISSUE THREAD

**Issue by efthimispegas** [jridgewell/gen-mapping#19]
Hello @jridgewell I see that you have not made a release of v.0.3.7 yet although you have mentioned in other duplicate issues that v.0.3.7 is out

https://github.com/jridgewell/gen-mapping/issues/18#issuecomment-2530804024

I would strongly suggest you not state information that is not valid, as many developers in the community have been thrown by these wrong statements.

Also, I would like to state that issue is still valid in many organizations where the public npmjs registry is not used and private artifactories are used instead. There the latest version (0.3.6) of @jridgewell/gen-mapping package is cached, causing the same issue. Currently, until a new release is out only workaround for resolving this issue is

// package.json
{
  //...
  "resolutions": {
    //...
    "@jridgewell/gen-mapping": "0.3.5"
  },
}

**Comment by jridgewell** [comment]
<img width="745" alt="Screenshot 2024-12-11 at 2 02 44 PM" src="https://github.com/user-attachments/assets/0e025a39-fd14-4a05-8be0-1c88b6e845a7" />

I removed it because of https://github.com/jridgewell/sourcemaps/issues/14. I am not ready to release a new version because I keep finding new issues.

> Also, I would like to state that issue is still valid in many organizations where the public npmjs registry is not used and private artifactories are used instead

If your private registry is causing you problems, I suggest you file issues with them.
